stream.properties = {
    channelmix.upmix        = true
    channelmix.upmix-method = psd
    channelmix.mix-lfe      = true
    channelmix.lfe-cutoff   = 150
    channelmix.fc-cutoff    = 12000
    channelmix.rear-delay   = 12.0
}




