 
context.modules = [
{   name = libpipewire-module-combine-stream
    args = {
        combine.mode = sink
        node.name = "combine_sink_7_1"
        node.description = "My 7.1 Combine Sink"
        combine.latency-compensate = false
        combine.props = {
            audio.position = [ FL FR FC LFE SL SR RL RR ]
        }
        stream.props = {
                stream.dont-remix = true      # link matching channels without remixing
        }
        stream.rules = [
            {   matches = [
                    {   media.class = "Audio/Sink"
                        node.name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
                    } ]
                actions = { create-stream = {
                        combine.audio.position = [ FL FR ]
                        audio.position = [ FL FR ]
                } } }
            {   matches = [
                    {   media.class = "Audio/Sink"
                        node.name = "alsa_output.usb-DisplayLink_Plugable_UD-ULTC4K_61088212-02.analog-stereo"
                    } ]                                                                                                                                                     
                actions = { create-stream = {                                                                                                                               
                        combine.audio.position = [ FC FC ]                                                                                                                  
                        audio.position = [ FL FR ]
                } } }
            {   matches = [
                    {   media.class = "Audio/Sink"
                        node.name = "bluez_output.FC_58_FA_DF_40_9C.1"
                    } ]
                actions = { create-stream = {
                        combine.audio.position = [ SR SR ]
                        audio.position = [ FL FR ]
                } } }
            {   matches = [
                    {   media.class = "Audio/Sink"
                        node.name = "bluez_output.00_00_51_00_10_28.1"
                    } ]
                actions = { create-stream = {   
                        combine.audio.position = [ SL SL ]
                        audio.position = [ FL FR ]
                } } }
            {   matches = [
                    {   media.class = "Audio/Sink"
                        node.name = "bluez_output.6E_07_47_86_6B_13.1"
                    } ]
                actions = { create-stream = {
                        combine.audio.position = [ RR RR ]
                        audio.position = [ FL FR ]
                } } }
            {   matches = [
                    {   media.class = "Audio/Sink"
                        node.name = "bluez_output.A8_4A_10_1E_40_55.1"
                    } ]
                actions = { create-stream = {
                        combine.audio.position = [ RL RL ]
                        audio.position = [ FL FR ]
                } } }
            {   matches = [
                    {   media.class = "Audio/Sink"
                        node.name = "alsa_output.usb-GeneralPlus_USB_Audio_Device-00.analog-stereo"
                    } ]
                actions = { create-stream = {
                        combine.audio.position = [ LFE LFE ]
                        audio.position = [ FL FR ]
                } } }
        ]
    }
}
]
